### ISSUE TITLE
response.ok not documented

### ISSUE THREAD

**Issue by JESii** [nkronlage/JavaScripture#30]
Maybe I'm missing something, but on the response page [https://www.javascripture.com/Response](https://www.javascripture.com/Response), I don't see `response.ok` (and others such as `status` or `statusText`) included in the properties list. Compare to [https://developer.mozilla.org/en-US/docs/Web/API/Response](https://developer.mozilla.org/en-US/docs/Web/API/Response)

**Comment by nkronlage** [comment]
Fixed with be4c715f135bf20195f9abb5e0cf5a192c2029c0. Thanks for reporting this!
